// Generated by CoffeeScript 2.5.1
(function() {
  var coffeescript, cssmin, dest, minify, pug, sass, src, watch;

  ({watch, src, dest} = require("gulp"));

  sass = require("gulp-sass");

  sass.compiler = require("sass");

  cssmin = require("gulp-cssmin");

  coffeescript = require("gulp-coffeescript");

  minify = require("gulp-minify");

  pug = require("gulp-pug");

  exports.default = function() {
    watch('pug/**/*.pug', function(cb) {
      src(['pug/**/*.pug', '!pug/layouts/**/*.pug', '!pug/inc/**/*.pug']).pipe(pug({
        prettiy: false
      })).pipe(dest('../app/tpl'));
      cb();
    });
    watch('sass/**/*.sass', function(cb) {
      src(['sass/**/*.sass', '!sass/inc/**/*.sass']).pipe(sass()).pipe(cssmin()).pipe(dest('../public/css/')).pipe(dest('css/'));
      src(['pug/**/*.pug', '!pug/layouts/**/*.pug', '!pug/inc/**/*.pug']).pipe(pug({
        prettiy: false
      })).pipe(dest('../app/tpl'));
      cb();
    });
    watch('coffee/**/*.coffee', function(cb) {
      src('coffee/**/*.coffee').pipe(coffeescript()).pipe(minify({
        ext: {
          min: '.js'
        },
        noSource: true
      })).pipe(dest('../public/js')).pipe(dest('js/'));
      src(['pug/**/*.pug', '!pug/layouts/**/*.pug', '!pug/inc/**/*.pug']).pipe(pug({
        prettiy: false
      })).pipe(dest('../app/tpl'));
      cb();
    });
  };

}).call(this);
